// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommandServer
{
    internal sealed partial class Vsix
    {
        public const string Id = "CommandServer.a6e62ec2-6d8d-4bc3-b899-5858e78a1ae1";
        public const string Name = "CommandServer";
        public const string Description = @"Adds support for running arbitrary commands via file-based RPC. Designed for use with voice-control systems such as Talon.Adds support for running arbitrary commands via file-based RPC.";
        public const string Language = "en-US";
        public const string Version = "1.0.0.1";
        public const string Author = "John Efford";
        public const string Tags = "";
    }
}
