// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CommandServer
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string CommandServerOutputWindowString = "f5b52007-cc1b-485a-97e8-e19f2b4f6e99";
        public static Guid CommandServerOutputWindow = new Guid(CommandServerOutputWindowString);

        public const string CommandServerString = "b727b8d1-2065-4540-a5b2-e581ba31b362";
        public static Guid CommandServer = new Guid(CommandServerString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int ReceiveCommand = 0x0100;
        public const int ServerInit = 0x0110;
    }
}